#Mon Feb 24 17:58:32 EET 2025
micronaut:
  application.name: rrtb-daily-post-lambda
  serde:
    deserialization:
      fail-on-null-for-primitives: false
      ignore-unknown: true
      strict-nullable: false
    serialization:
      always-serialize-errors-as-list: true
      inclusion: NON_EMPTY

