name: CI

on:
  push:
    branches: [ "master", "RRTB-*" ]
  pull_request:
    branches: [ "master" ]
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: CDK Synth
        working-directory: rrtb_infra
        run: mvn -B exec:java

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.jar
            rrtb_infra/cdk.out
          retention-days: 7 